
import Banner from '@/Components/home/banner'
import HeroSection from '@/Components/home/HeroSection'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Eccomerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection/>
        <Banner/>
      </main>
    </>
  )
}
